---
title: "PUG Blog Project: COVID-19 Impact on Individual Economic Health"
authors: Maggie Smith & Sammy Phillips
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggrepel)
library(GGally)
library(ggmosaic)
```

# Introduction

# Clustering Analysis

```{r}
kmeans_data <- read.csv("~/Desktop/DataScience/git/Blog-Girls-Who-Code/kmeans_data.csv") 

set.seed(23)
km2_out <- kmeans(kmeans_data, centers = 2, nstart = 20)
km2_out$centers

kmeans_data2 <- kmeans_data %>%
  mutate(clust2 = as.character(km2_out$cluster))

set.seed(23)
km4_out <- kmeans(kmeans_data, centers = 4, nstart = 20)
km4_out$centers

kmeans_data2 <- kmeans_data2 %>%
  mutate(clust4 = as.character(km4_out$cluster))

set.seed(23)
km5_out <- kmeans(kmeans_data, centers = 5, nstart = 20)
km5_out$centers

kmeans_data2 <- kmeans_data2 %>%
  mutate(clust5 = as.character(km5_out$cluster))

set.seed(23)
km7_out <- kmeans(kmeans_data, centers = 7, nstart = 20)
km7_out$centers

kmeans_data2 <- kmeans_data2 %>%
  mutate(clust7 = as.character(km7_out$cluster))

set.seed(23)
km11_out <- kmeans(kmeans_data, centers = 11, nstart = 20)
km11_out$centers

kmeans_data2 <- kmeans_data2 %>%
  mutate(clust11 = as.character(km11_out$cluster))
```

```{r}
fig <- matrix(NA, nrow=15, ncol=2)

set.seed(75)
for (i in 1:15){
  fig[i,1] <- i
  fig[i,2] <- kmeans(kmeans_data
                    , centers=i
                    , nstart=20)$tot.withinss
}

ggplot(data = as.data.frame(fig), aes(x = V1, y = V2)) +
  geom_point() + 
  geom_line() +
  scale_x_continuous(breaks=c(1:15)) +
  labs(x = "K", y = expression("Total W"[k]))
```

```{r}
vars <- c("ECON4A", "ECON4B", "HHINCOME", "EDUCATION", "AGE7")

ggpairs(data = kmeans_data2
        , aes(color = clust4) 
        , columns = vars
        , upper = list(continuous = "blank"))
```

```{r}
ggplot(kmeans_data2, aes(x = HHINCOME, group = clust4, fill = clust4)) +
    geom_density(adjust = 5) + 
  labs(title = "Distribution of Income By Cluster", 
       x = "Income", 
       fill = "Cluster Assignment") + 
  facet_wrap(~clust4)

ggplot(kmeans_data2, aes(x = AGE7, group = clust4, fill = clust4)) +
    geom_density(adjust = 5) +
  labs(title = "Distribution of Age By Cluster", 
       x = "Age Group", 
       fill = "Cluster Assignment") +
  facet_wrap(~clust4)

ggplot(data = kmeans_data2, aes(x=ECON4A, group = clust4, fill=clust4)) +
  geom_density(adjust = 5) +
  labs(title = "Distribution of ECON4A Responses by Cluster", 
       x = "ECON4A Responses", 
       fill = "Cluster Assignment") +
  facet_wrap(~clust4)

ggplot(data = kmeans_data2, aes(x=ECON4B, group = clust4, fill=clust4)) +
  geom_density(adjust = 5) +
  labs(title = "Distribution of ECON4B Responses by Cluster", 
       x = "ECON4B Responses", 
       fill = "Cluster Assignment") +
  facet_wrap(~clust4)
```

# Post-Clustering Analysis

```{r}
post_cluster_vars <- read.csv("~/Desktop/DataScience/git/Blog-Girls-Who-Code/post_cluster_data.csv")
  
alL_vars_data <- post_cluster_vars %>% 
  left_join(kmeans_data2, by = "AGE7") 
```

```{r}
ggplot(alL_vars_data, aes(x = clust4, fill = GENDER2)) +
  geom_bar(position = "fill") +
  labs(title = "Gender Proportions by Cluster Assignment", 
       x = "Cluster Assignment", 
       y = "Proportion",
       fill = "Gender") 

ggplot(alL_vars_data, aes(x = clust4, fill = RACETH2)) +
  geom_bar(position = "fill") +
  labs(title = "Race Proportions by Cluster Assignment", 
       x = "Cluster Assignment", 
       y = "Proportion", 
       fill = "Race")

ggplot(alL_vars_data, aes(x = clust4, fill = P_DENSE2)) +
  geom_bar(position = "fill") +
  labs(title = "Population Density Proportions by Cluster Assignment", 
       x = "Cluster Assignment",  
       y = "Proportion",
       fill = "Population Density")
```

```{r}
ggplot(alL_vars_data, aes(x = clust4, fill = ECON6A_2)) +
  geom_bar(position = "fill") +
  labs(title = "Proportions of Unemployment Insurance Status Cluster Assignment", 
       x = "Cluster Assignment", 
       y = "Proportion", 
       fill = "Unemployment Insurance Status")

ggplot(alL_vars_data, aes(x = clust4, fill = ECON6C_2)) +
  geom_bar(position = "fill") +
  labs(title = "Proportions of TANF Status Cluster Assignment", 
       x = "Cluster Assignment", 
       y = "Proportion", 
       fill = "TANF Status")

ggplot(alL_vars_data, aes(x = clust4, fill = ECON5A_B2)) +
  geom_bar(position = "fill") +
  labs(title = "Proportions of Food Security Levels Status Cluster Assignment", 
       x = "Cluster Assignment", 
       y = "Proportion", 
       fill = "Level")
```

# Limitations & Extensions 

# Conclusion